text justification init
kamilnapiontek/javaCourse pull request #1
Opened 2022-09-19 17:12 UTC by kamilnapiontek

2022-09-19 17:14 UTC, Y0ucandev requested changes

2022-09-19 17:14 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +
dodaj kod ktory wykonuje zadanie

2022-10-09 21:22 UTC, kamilnapiontek commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +
coś tutaj napsułem i nie mogę Ci tego wysłać
![image](https://user-images.githubusercontent.com/43855312/194780005-90bc2879-b020-4781-876e-2075d8cdf04a.png)

2022-10-09 21:51 UTC, Y0ucandev requested changes

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/Main.java
> +        textJustification.writeText(new ArrayList<>(Arrays.asList("This","is","an","example","of","text","justification")),16);
bardziej elegancko robi sie List.of liste. Plus tez taki ze jest niemutowalna a chyba nigdzie jej nei zmieniasz pozniej wiec tym bardziej popraw to

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/Main.java
> +        System.out.println("***************************");
po co ten smieciowy log ?

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +        switch (currentLine.size()) {
refactor zrob na switcha z javy 14+

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                int numberOfLetters2 = 0;
jakos lepiej to nazwij. Nazywanie zmiennej tak samo jak poprzedniej i dodawanie 2 to nic dobrego

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                int numberOfLetters = 0;
raczej nie number tylko count. to jak po polsku liczba i ilosc

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                System.out.print(currentLine.get(0));
do czego ten log ?

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                System.out.print(currentLine.get(0));
jezeli wyswietla co kolwiek co jest uzyteczne do wyniku to lepiej miec jednego stringa ktorego budujesz tak aby w jednej zmiennej byl caly ten wynikowy string. Unikaj tego smieciowego logowania. Bedzie trudniej ale poprawnie

2022-10-09 21:51 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +        int i = 0;
czym jest niby ta zmienna bo i nic nie mowi. nazwij to lepiej

2022-10-09 21:53 UTC, Y0ucandev commented
skonfliktowales sie sam ze soba :D
naprawimy to na zajeciach. Zeby samemu sie skonfliktowac sam ze soba to
sztuka :D

niedz., 9 paź 2022 o 23:22 kamilnapiontek ***@***.***>
napisał(a):

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/main/java/org/example/homework/textjustification/TextJustification.java
> <https://github.com/kamilnapiontek/javaCourse/pull/1#discussion_r990841783>
> :
>
> > @@ -0,0 +1,5 @@
>
> +package org.example.homework.textjustification;
>
> +
>
> +public class TextJustification {
>
> +
>
>
> coś tutaj napsułem i nie mogę Ci tego wysłać
> [image: image]
> <https://user-images.githubusercontent.com/43855312/194780005-90bc2879-b020-4781-876e-2075d8cdf04a.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kamilnapiontek/javaCourse/pull/1#discussion_r990841783>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2YD7QL2CU5N2FFA62ATG7DWCMZSXANCNFSM6AAAAAAQQJRMLY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-17 17:10 UTC, kamilnapiontek commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +        int i = 0;
wolna przestrzeń pomiędzy wyrazami

2022-10-17 20:34 UTC, kamilnapiontek commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                System.out.print(currentLine.get(0));
służy do wypisania pierwszego wyrazu w linii, nie może być w pętli bo pętla zaczyna się od wypisania " ", a jeśli odwrócę kolejność to na końcu powstanie niechciana spacja

2022-10-17 20:57 UTC, Y0ucandev requested changes

2022-10-17 20:57 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +                System.out.print(currentLine.get(0));
wiec najlepiej wydzielic to do zmiennej bo za 2 tygodnie nie bedziesz pamietal co ten log robil

2022-10-17 20:57 UTC, Y0ucandev commented on src/main/java/org/example/homework/textjustification/TextJustification.java
> +        int i = 0;
to zmien jej nazwe aby odzwierciedlala twoje intencje bo na ten moment to sie nazywa i

2022-10-17 20:58 UTC, Y0ucandev commented
Nazwa commita ma mowic co zostalo zrobione, nie nazywaj ich 1.0 2.0 3.0.

2022-10-18 15:58 UTC, Y0ucandev approved these changes

2022-10-18 15:58 UTC, merged